version: '3'

services:
  db-gps: # ideal: ser alterado para db-<nome-do-projeto>, alterar também na linha abaixo de "depends_on" da api
    container_name: postgres-gps
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - /data/postgres:/data/postgres

  api: # ideal: ser alterado para api-<nome-do-projeto>
    container_name: backend-gps # ideal: ser alterado para backend-<nome-do-projeto>
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db-gps
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: yarn start:dev

networks:
  postgres:
    driver: bridge
